### ISSUE TITLE
TypeScript errors not displayed

### ISSUE THREAD

**Issue by danielearwicker** [electron-userland/electron-forge-templates#27]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

When I create a new project with:

```
electron-forge init my-new-project --template=react-typescript
```

It initially has a type error, because it requires `electron-compile` which doesn't yet have typings.

But when the project is run with `electron-forge start` the type errors don't get displayed anywhere. It just silently runs. Ideally the console should display type errors prominently.

Also the initially created project should not error - I've [submitted a PR for embedded typings](https://github.com/electron/electron-compile/pull/219) in `electron-compile` to try to resolve this.

**Comment by anaisbetts** [comment]
We don't actually want to stop the app from running even if there are type errors, the IDE and the linter can do the job of reporting type errors. This is hard because our compiler model doesn't take the entire project into account, or else we'd recompile the entire app for every file.

I would take a PR to the template to add typechecking as part of the lint step though, I think that's a Good Idea
