### ISSUE TITLE
Update angular template to v4

### ISSUE THREAD

**Issue by MarshallOfSound** [electron-userland/electron-forge-templates#43]

**Comment by richardabear** [comment]
Yes this would be immensely helpfull I have to manually update it everytime i create a new project :) if you guys could update the electron-forge angular2 template to use angular4 that would be amazing! :) Thanks!

**Comment by malept** [comment]
I don't think any of the core members are very familiar with Angular, so a PR from a community member would be greatly appreciated.

**Comment by LukeTOBrien** [comment]
I would say that instead of replacing the template, you could try use [Angular-cli](https://cli.angular.io/)  
Give the developers the control over updating.  
I also had difficulty installing the routing module, 

We are now on Angular 6, so this issue is outdated and you will always have to replace with the latest.  
Instead I think an easy way for developers to upgrade the template when they need to.

**Comment by malept** [comment]
There's an old thread with one of the Angular core developers here about integration with angular-cli: https://github.com/electron-userland/electron-forge-templates/pull/47#issuecomment-336470912

Regarding this issue, I'm closing it because we're probably going to rework all of the templates for Forge v6 and have bundler-specific templates (e.g., webpack, parcel) instead of framework-specific templates.
